server:
  port: 8001
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
  mvc:
    view:
      prefix: /templates/
      suffix: .html
mybatis-plus:
  configuration:
    shrink-whitespaces-in-sql: true #从SQL中删除多余的空格字符
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml
short-link:
  domain:
    default: nurl.ink:8001
  stats:
    locale:
      amap-key: 0e036d9efb2606dc89f858e31ea7593d
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer'
      details:
        - nageoffer.com
